config/routes.rb
Rails.application.routes.draw do
  root 'logins#index'
  resources :tests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :apis do
    collection do
      get 'registeruser'
      get 'login'
      get 'pactnumber'
      post 'idfont'
      post 'idback'
      get 'registerready'
      get 'uploader'
      post 'attchment'
      get 'getattchment'
      get 'deleteattch'
      get 'pact'
      get 'getseller'
      get 'mypact'
      get 'getopenid'
      get 'getpartid'
      get 'getbuinesname'
      get 'getproduct'
      get 'checkpwd'
      get 'setpwd'
      get 'authpwd'
      get 'getcurrentseller'
      get 'getinvitecode'
      get 'myinvitecode'
      get 'getsalesman'
      get 'getup'
      get 'test'
      get 'sendtest'
      get 'getcommission'
      get 'checkwithdrawcode'
      get 'getinvoice'
      get 'setinvoice'
    end
  end
  resources :idcards
  resources :users do
    resources :useramounts
    resources :withdraws
  end
  resources :wxpayments do
    collection do
      get 'information'
      post 'notify'
      get 'payuser'
      get 'manualnotify'
    end
  end
  resources :getopenids
  resources :dgts do
    resources :ecas
  end
  resources :products
  resources :orders
  resources :profits
  resources :admins
  resources :logins
  resources :dgtorders do
    collection do
      get 'sends'
      get 'deldeliveorders'
      get 'setinvoicestatus'
      get 'print'
    end

  end
  resources :delives
  resources :wxusers
  resources :pacts
  resources :dgtfees
  resources :buycars do
    resources :deliveorders
  end
  resources :busines
  resources :userprofits
  resources :rechargeusers do
    collection do
      get 'getuser'
    end
  end
  resources :giveaways do
    resources :giveawaybusines
    resources :giveawayproducts
  end
resources :counts do
  collection do
    get 'mapscount'
  end
end
  #resources :calcommissions
resources :userinoutcounts do

end
  resources :sendsms do
    collection do
      get 'sendvcode'
    end
  end
  resources :apiv2 do
    collection do
      get 'getseller'
      get 'getsellersearch'
    end
  end
  resources :settings do
    collection do
      get 'init_busine_pinyin'
      get 'changecupratio'
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

app/models/busine.rb
class Busine < ApplicationRecord
  has_many :pacts
  has_many :buycars
  has_many :invoices
  #has_many :busineatts
end

app/models/buycar.rb
class Buycar < ApplicationRecord
  belongs_to :busine
  has_many :orders
  has_many :deliveorders
  has_many :attchorders
end

app/models/delive.rb
class Delive < ApplicationRecord
end

app/models/dgt.rb
class Dgt < ApplicationRecord
  has_many :products
  has_many :dgtfees
  has_many :ecas
end

app/models/dgtfee.rb
class Dgtfee < ApplicationRecord
  belongs_to :dgt
end

app/models/eca.rb
class Eca < ApplicationRecord
  belongs_to :dgt
end

app/models/giveaway.rb
class Giveaway < ApplicationRecord
  has_many :giveawaybusines, dependent: :destroy
  has_many :giveawayproducts, dependent: :destroy
end

app/models/idcard.rb
class Idcard < ApplicationRecord
  has_attached_file :idfront, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/idront/:id/:basename.:extension"
  do_not_validate_attachment_file_type :idfront
  has_attached_file :idback, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/idback/:id/:basename.:extension"
  do_not_validate_attachment_file_type :idback
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :busine
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :buycar
end

app/models/pact.rb
class Pact < ApplicationRecord
  belongs_to :user
  has_many :attchments
  belongs_to :busine
  has_many :attchproducts, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :dgt
  has_attached_file :productimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :productimg
end

app/models/profit.rb
class Profit < ApplicationRecord
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/testlog.rb
class Testlog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  has_many :pacts
  has_many :useramounts
  has_many :userpwds
  has_many :commissions
  has_many :withdraws
  
  has_attached_file :idfontimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/idfontimgs/:id/:basename.:extension"
  do_not_validate_attachment_file_type :idfontimg
  has_attached_file :idbackimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/idbackimgs/:id/:basename.:extension"
  do_not_validate_attachment_file_type :idbackimg

  has_many :childrens, class_name: "User", foreign_key: "up_id"
  belongs_to :parent, class_name: "User", foreign_key: "up_id"

  has_many :invitecodes

end

app/models/userpwd.rb
class Userpwd < ApplicationRecord
  has_secure_password
  belongs_to :user
end

app/models/withdraw.rb
class Withdraw < ApplicationRecord
  belongs_to :user
end

app/models/wxuser.rb
class Wxuser < ApplicationRecord
end

app/controllers/dgts_controller.rb
class DgtsController < ApplicationController
  before_action :set_dgt, only: [:show, :edit, :update, :destroy]
  def index
    @dgts=Dgt.all
    @dgtfees=Dgtfee.all
  end

  def edit
    @dgt=Dgt.find(params[:id])

  end

  def new
    @dgt = Dgt.new
  end

  def create
    @dgt = Dgt.new(dgt_params)

    respond_to do |format|
      if @dgt.save
        format.html { redirect_to dgts_path, notice: 'Dgt was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @dgt.update(dgt_params)
        format.html { redirect_to dgts_path, notice: 'Dgt was successfully updated.' }
        format.json { render :show, status: :ok, location: @dgt }
      else
        format.html { render :edit }
        format.json { render json: @dgt.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @dgt.destroy
    respond_to do |format|
      format.html { redirect_to dgts_path, notice: '删除成功' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_dgt
    @dgt = Dgt.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dgt_params
    params.require(:dgt).permit(:name ,:contact, :phone)
  end

end

app/helpers/dgts_helper.rb
module DgtsHelper
end

app/views/dgts/_form.html.erb
<div class="ibox-content form-horizontal m-t">
  <div class="form-group">
    <%= form_for(@dgt,:html => {:class=>'form-horizontal m-t',:multipart => true}) do |f| %>
        <div class="form-group">
          <label class="col-sm-3 control-label">厂商名称：</label>
          <div class="col-sm-5">
            <%= f.text_field :name,class:"form-control" %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">联系人：</label>
          <div class="col-sm-5">
            <%= f.text_field :contact,class:"form-control" %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">联系电话：</label>
          <div class="col-sm-5">
            <%= f.text_field :phone,class:"form-control" %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label"></label>
          <div class="col-sm-5 text-right">
            <%= f.submit '确定',class: "btn btn-w-m btn-primary " %>&nbsp;<%= link_to "返回",dgts_url,class: "btn btn-w-m btn-primary " %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/dgts/edit.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>编辑厂商</h3>
    </div>
<%= render 'form', dgt: @dgt %>
  </div>
</div>
<%=render 'layerend' %>

app/views/dgts/index.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>厂商管理</h3>
    </div>
    <div class="ibox-content">
      <table class="table table-hover table-bordered text-center">
        <thead>
        <tr>
          <th class="text-center">厂商名称</th>
          <th class="text-center">联系人</th>
          <th class="text-center">联系电话</th>
          <th class="text-center">营业额</th>
          <th class="text-center">已支付额</th>
          <th class="text-center">操作</th>
        </tr>
        </thead>
        <tbody>
        <% @dgts.each do |dgt| %>
            <tr>
              <td><%= dgt.name %></td>
              <td><%= dgt.contact %></td>
              <td><%= dgt.phone %></td>
              <td>
              <% dgtfees=dgt.dgtfees %>
                <%= dgtfees.sum('amount') %>
              </td>
              <td><%= dgt.amountsub %></td>
              <td><%= link_to '编辑',edit_dgt_path(dgt) %>
                <%= link_to '删除', dgt, method: :delete, data: { confirm: '确认删除?' } %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <%= link_to "新增",new_dgt_path,class: "btn btn-w-m btn-primary pull-right" %>
      <br>
    </div>
  </div>
</div>
<%=render 'layerend' %>

app/views/dgts/new.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>新增厂商</h3>
    </div>
    <%= render 'form', dgt: @dgt %>
  </div>
</div>
<%=render 'layerend' %>