config/routes.rb
Rails.application.routes.draw do
  root 'logins#index'
  resources :tests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :apis do
    collection do
      get 'registeruser'
      get 'login'
      get 'pactnumber'
      post 'idfont'
      post 'idback'
      get 'registerready'
      get 'uploader'
      post 'attchment'
      get 'getattchment'
      get 'deleteattch'
      get 'pact'
      get 'getseller'
      get 'mypact'
      get 'getopenid'
      get 'getpartid'
      get 'getbuinesname'
      get 'getproduct'
      get 'checkpwd'
      get 'setpwd'
      get 'authpwd'
      get 'getcurrentseller'
      get 'getinvitecode'
      get 'myinvitecode'
      get 'getsalesman'
      get 'getup'
      get 'test'
      get 'sendtest'
      get 'getcommission'
      get 'checkwithdrawcode'
      get 'getinvoice'
      get 'setinvoice'
    end
  end
  resources :idcards
  resources :users do
    resources :useramounts
    resources :withdraws
  end
  resources :wxpayments do
    collection do
      get 'information'
      post 'notify'
      get 'payuser'
      get 'manualnotify'
    end
  end
  resources :getopenids
  resources :dgts do
    resources :ecas
  end
  resources :products
  resources :orders
  resources :profits
  resources :admins
  resources :logins
  resources :dgtorders do
    collection do
      get 'sends'
      get 'deldeliveorders'
      get 'setinvoicestatus'
      get 'print'
    end

  end
  resources :delives
  resources :wxusers
  resources :pacts
  resources :dgtfees
  resources :buycars do
    resources :deliveorders
  end
  resources :busines
  resources :userprofits
  resources :rechargeusers do
    collection do
      get 'getuser'
    end
  end
  resources :giveaways do
    resources :giveawaybusines
    resources :giveawayproducts
  end
resources :counts do
  collection do
    get 'mapscount'
  end
end
  #resources :calcommissions
resources :userinoutcounts do

end
  resources :sendsms do
    collection do
      get 'sendvcode'
    end
  end
  resources :apiv2 do
    collection do
      get 'getseller'
      get 'getsellersearch'
    end
  end
  resources :settings do
    collection do
      get 'init_busine_pinyin'
      get 'changecupratio'
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

app/models/busine.rb
class Busine < ApplicationRecord
  has_many :pacts
  has_many :buycars
  has_many :invoices
  #has_many :busineatts
end

app/models/buycar.rb
class Buycar < ApplicationRecord
  belongs_to :busine
  has_many :orders
  has_many :deliveorders
  has_many :attchorders
end

app/models/delive.rb
class Delive < ApplicationRecord
end

app/models/dgt.rb
class Dgt < ApplicationRecord
  has_many :products
  has_many :dgtfees
  has_many :ecas
end

app/models/dgtfee.rb
class Dgtfee < ApplicationRecord
  belongs_to :dgt
end

app/models/eca.rb
class Eca < ApplicationRecord
  belongs_to :dgt
end

app/models/giveaway.rb
class Giveaway < ApplicationRecord
  has_many :giveawaybusines, dependent: :destroy
  has_many :giveawayproducts, dependent: :destroy
end

app/models/idcard.rb
class Idcard < ApplicationRecord
  has_attached_file :idfront, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/idront/:id/:basename.:extension"
  do_not_validate_attachment_file_type :idfront
  has_attached_file :idback, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/idback/:id/:basename.:extension"
  do_not_validate_attachment_file_type :idback
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :busine
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :buycar
end

app/models/pact.rb
class Pact < ApplicationRecord
  belongs_to :user
  has_many :attchments
  belongs_to :busine
  has_many :attchproducts, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :dgt
  has_attached_file :productimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :productimg
end

app/models/profit.rb
class Profit < ApplicationRecord
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/testlog.rb
class Testlog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  has_many :pacts
  has_many :useramounts
  has_many :userpwds
  has_many :commissions
  has_many :withdraws
  
  has_attached_file :idfontimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/idfontimgs/:id/:basename.:extension"
  do_not_validate_attachment_file_type :idfontimg
  has_attached_file :idbackimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/idbackimgs/:id/:basename.:extension"
  do_not_validate_attachment_file_type :idbackimg

  has_many :childrens, class_name: "User", foreign_key: "up_id"
  belongs_to :parent, class_name: "User", foreign_key: "up_id"

  has_many :invitecodes

end

app/models/userpwd.rb
class Userpwd < ApplicationRecord
  has_secure_password
  belongs_to :user
end

app/models/wxuser.rb
class Wxuser < ApplicationRecord
end

app/views/admins/_form.html.erb
<script>
    $(document).ready(function(){

        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green'
        });

        var elem = document.querySelector('.js-switch');
        var init = new Switchery(elem);

        if($('#status').val()==''){
            $('#status').val('1');
        }

        if($('#status').val()=='1')
        {
            //$('.js-switch').prop('checked', true);
            //$('.js-switch').attr('checked');
            setSwitchery(init, true);

        }else
        {
            //$('.js-switch').prop('checked', false);
            setSwitchery(init, false);
            //$('.js-switch').attr('unchecked');
        }

        function setSwitchery(switchElement, checkedBool) {
            if((checkedBool && !switchElement.isChecked()) || (!checkedBool && switchElement.isChecked())) {
                switchElement.setPosition(true);
                switchElement.handleOnchange(true);
            }
        }

        if($('#dgtid').val()==''){
            $('#dgtid').val('0');
        }

        toastr.options = {
            "closeButton": true,
            "debug": false,
            "progressBar": false,
            "positionClass": "toast-top-full-width",
            "onclick": null,
            "showDuration": "400",
            "hideDuration": "1000",
            "timeOut": "7000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }

        $('#selectdgt').change(function(){
            $('#dgtid').val($(this).val());
        });

        if($('#dgtid').val()!=''){
            $('#selectdgt').val($('#dgtid').val());
        }


        $('#smt').click(function(){
            if (elem.checked){
                $('#status').val('1');
            }else
            {
                $('#status').val('0');
            }

        });


    });

</script>
<div class="col-md-12 ibox ibox-content">
  <div class="ibox-content form-horizontal m-t">
    <div class="form-group">
      <%= form_for(@admin,:html => {:class=>'form-horizontal m-t',:multipart => true}) do |f| %>

          <div class="form-group">
            <label class="col-sm-3 control-label">姓名：</label>
            <div class="col-sm-5">
              <%= f.text_field :username,class:"form-control" %>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">账号：</label>
            <div class="col-sm-5">
              <% if @admin.id %>
              <%= f.text_field :login,class:"form-control",'readonly':'true' %>
                  <% else %>
                  <%= f.text_field :login,class:"form-control" %>
              <% end %>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">密码：</label>
            <div class="col-sm-5">
              <%= f.password_field :password,class:"form-control" %>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">确认密码：</label>
            <div class="col-sm-5">
              <%= f.password_field :password_confirmation,class:"form-control" %>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">隶属于：</label>
            <div class="col-sm-5">
              <%= f.hidden_field :dgt_id, id:'dgtid' %>
              <select class="form-control m-b" id="selectdgt">
                <option value=0>系统管理员</option>
                <% @dgts.each do |dgt| %>
                    <option value=<%= dgt.id %> ><%= dgt.name %></option>
                <% end %>
              </select>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">状态：</label>
            <div class="col-sm-5">
              <%= f.hidden_field :status,class:"form-control",id:'status' %>
              <input type="checkbox" class="js-switch" checked />
            </div>
          </div>


          <div class="form-group">
            <label class="col-sm-3 control-label"></label>
            <div class="col-sm-5 text-right">
              <%= f.submit '确定',class: "btn btn-w-m btn-primary ",id:'smt' %>&nbsp;<%= link_to "返回",admins_path,class: "btn btn-w-m btn-primary " %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/edit.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>编辑产品</h3>
    </div>
    <%= render 'form', product: @product %>
  </div>
</div>
<%=render 'layerend' %>

app/views/admins/index.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>管理员</h3>
    </div>
    <div class="ibox-content">
      <table class="table table-hover table-bordered text-center">
        <thead>
        <tr>
          <th class="text-center">姓名</th>
          <th class="text-center">账号</th>
          <th class="text-center">隶属于</th>
          <th class="text-center">状态</th>
          <th class="text-center">操作</th>
        </tr>
        </thead>
        <tbody>
        <% @admins.each do |admin| %>
            <tr>
              <td><%= admin.username %></td>
              <td><%= admin.login %></td>
              <td>


                <% dgt=Dgt.where('id = ?',admin.dgt_id) %>
                <% if dgt.count>0 %>
                <%= dgt.first.name %>
                    <% else %>
                    系统管理员
                <% end %>

              </td>
              <td>
                <% if admin.status==0 %>
                锁定
                    <% else %>
                正常
                <% end %>
              </td>

              <td><%= link_to '编辑',edit_admin_path(admin) %>
                <% if admin.login != 'admin' %>
                <%= link_to '删除', admin, method: :delete, data: { confirm: '确认删除?' } %>
                    <% else %>
                &nbsp;
                    <% end %>
                    </td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <%= link_to "新增",new_admin_path,class: "btn btn-w-m btn-primary pull-right" %>
      <br>
    </div>
  </div>
</div>
<%=render 'layerend' %>

app/views/admins/new.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>新增管理员</h3>
    </div>
    <%= render 'form', admin: @admin %>
  </div>
</div>
<%=render 'layerend' %>