config/routes.rb
Rails.application.routes.draw do
  root 'logins#index'
  resources :tests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :apis do
    collection do
      get 'registeruser'
      get 'login'
      get 'pactnumber'
      post 'idfont'
      post 'idback'
      get 'registerready'
      get 'uploader'
      post 'attchment'
      get 'getattchment'
      get 'deleteattch'
      get 'pact'
      get 'getseller'
      get 'mypact'
      get 'getopenid'
      get 'getpartid'
      get 'getbuinesname'
      get 'getproduct'
      get 'checkpwd'
      get 'setpwd'
      get 'authpwd'
      get 'getcurrentseller'
      get 'getinvitecode'
      get 'myinvitecode'
      get 'getsalesman'
      get 'getup'
      get 'test'
      get 'sendtest'
      get 'getcommission'
      get 'checkwithdrawcode'
      get 'getinvoice'
      get 'setinvoice'
    end
  end
  resources :idcards
  resources :users do
    resources :useramounts
    resources :withdraws
  end
  resources :wxpayments do
    collection do
      get 'information'
      post 'notify'
      get 'payuser'
      get 'manualnotify'
    end
  end
  resources :getopenids
  resources :dgts do
    resources :ecas
  end
  resources :products
  resources :orders
  resources :profits
  resources :admins
  resources :logins
  resources :dgtorders do
    collection do
      get 'sends'
      get 'deldeliveorders'
      get 'setinvoicestatus'
      get 'print'
    end

  end
  resources :delives
  resources :wxusers
  resources :pacts
  resources :dgtfees
  resources :buycars do
    resources :deliveorders
  end
  resources :busines
  resources :userprofits
  resources :rechargeusers do
    collection do
      get 'getuser'
    end
  end
  resources :giveaways do
    resources :giveawaybusines
    resources :giveawayproducts
  end
resources :counts do
  collection do
    get 'mapscount'
  end
end
  #resources :calcommissions
resources :userinoutcounts do

end
  resources :sendsms do
    collection do
      get 'sendvcode'
    end
  end
  resources :apiv2 do
    collection do
      get 'getseller'
      get 'getsellersearch'
    end
  end
  resources :settings do
    collection do
      get 'init_busine_pinyin'
      get 'changecupratio'
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

app/models/busine.rb
class Busine < ApplicationRecord
  has_many :pacts
  has_many :buycars
  has_many :invoices
  #has_many :busineatts
end

app/models/buycar.rb
class Buycar < ApplicationRecord
  belongs_to :busine
  has_many :orders
  has_many :deliveorders
  has_many :attchorders
end

app/models/delive.rb
class Delive < ApplicationRecord
end

app/models/dgt.rb
class Dgt < ApplicationRecord
  has_many :products
  has_many :dgtfees
  has_many :ecas
end

app/models/dgtfee.rb
class Dgtfee < ApplicationRecord
  belongs_to :dgt
end

app/models/eca.rb
class Eca < ApplicationRecord
  belongs_to :dgt
end

app/models/giveaway.rb
class Giveaway < ApplicationRecord
  has_many :giveawaybusines, dependent: :destroy
  has_many :giveawayproducts, dependent: :destroy
end

app/models/idcard.rb
class Idcard < ApplicationRecord
  has_attached_file :idfront, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/idront/:id/:basename.:extension"
  do_not_validate_attachment_file_type :idfront
  has_attached_file :idback, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/idback/:id/:basename.:extension"
  do_not_validate_attachment_file_type :idback
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :busine
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :buycar
end

app/models/pact.rb
class Pact < ApplicationRecord
  belongs_to :user
  has_many :attchments
  belongs_to :busine
  has_many :attchproducts, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :dgt
  has_attached_file :productimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :productimg
end

app/models/profit.rb
class Profit < ApplicationRecord
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/testlog.rb
class Testlog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  has_many :pacts
  has_many :useramounts
  has_many :userpwds
  has_many :commissions
  has_many :withdraws
  
  has_attached_file :idfontimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/idfontimgs/:id/:basename.:extension"
  do_not_validate_attachment_file_type :idfontimg
  has_attached_file :idbackimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/idbackimgs/:id/:basename.:extension"
  do_not_validate_attachment_file_type :idbackimg

  has_many :childrens, class_name: "User", foreign_key: "up_id"
  belongs_to :parent, class_name: "User", foreign_key: "up_id"

  has_many :invitecodes

end

app/models/userpwd.rb
class Userpwd < ApplicationRecord
  has_secure_password
  belongs_to :user
end

app/models/withdraw.rb
class Withdraw < ApplicationRecord
  belongs_to :user
end

app/models/wxuser.rb
class Wxuser < ApplicationRecord
end

app/controllers/giveaways_controller.rb
class GiveawaysController < ApplicationController

  before_action :set_giveaway, only: [:show, :edit, :update, :destroy]
  def index
    @giveaways=Giveaway.all.order('id desc')
  end

  def new
    @giveaway = Giveaway.new
    @products=Product.all
    @giveawayproducts=@giveaway.giveawayproducts
  end

  def create
    @giveaway = Giveaway.new(giveaway_params)

    respond_to do |format|
      if @giveaway.save
        format.html { redirect_to edit_giveaway_path(@giveaway), notice: 'giveaway was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @giveawayproducts=@giveaway.giveawayproducts
    @giveawaybusines=@giveaway.giveawaybusines
    @busines=Busine.all
    @products=Product.all
  end

  def update
    respond_to do |format|
      if @giveaway.update(giveaway_params)
        format.html { redirect_to giveaways_path, notice: 'Giveaway was successfully updated.' }
        format.json { render :show, status: :ok, location: @giveaway }
      else
        format.html { render :edit }
        format.json { render json: @giveaway.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @giveaway.destroy
    respond_to do |format|
      format.html { redirect_to giveaways_path, notice: '删除成功' }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_giveaway
    @giveaway = Giveaway.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def giveaway_params
    params.require(:giveaway).permit(:name ,:enable,:begindate, :enddate,:buyproduct_id, :giveproduct_id,:buynum, :givenum, :once)
  end

end

app/helpers/giveaways_helper.rb
module GiveawaysHelper
end

app/views/giveaways/_editform.html.erb
<script>
    $(document).ready(function(){

        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green'
        });

if($('#enable').val()==''){
    $('#enable').val('1');
}
        if($('#enable').val()== '0' ){
            $('#enablecheck').iCheck('uncheck');
        }else{
            $('#enablecheck').iCheck('check');
        }
            $('#enablecheck').on('ifChecked',function(event){
                $('#enable').val(1);
            });
        $('#enablecheck').on('ifUnchecked',function(event){
            $('#enable').val(0);
        });

        if($('#once').val()==''){
            $('#once').val('1');
        }

        if($('#once').val()== '0' ){
            $('#oncecheck').iCheck('uncheck');
        }else{
            $('#oncecheck').iCheck('check');
        }
        $('#oncecheck').on('ifChecked',function(event){
            $('#once').val(1);
        });
        $('#oncecheck').on('ifUnchecked',function(event){
            $('#once').val(0);
        });

        $('#buyproductselect').change(function(){
            $('#buyproductid').val($(this).val());
        });

        if($('#buyproductid').val()!=''){
            $('#buyproductselect').val($('#buyproductid').val());
        }

        $('#giveproductselect').change(function(){
            $('#giveproductid').val($(this).val());
        });

        if($('#giveproductid').val()!=''){
            $('#giveproductselect').val($('#giveproductid').val());
        }

        $('#selectproduct').change(function(){
            $('#productInput').val($(this).val());
        });

        $('#selectbusine').change(function(){
            $('#busineInput').val($(this).val());
        });


        $("#data_1 .input-group.date").datepicker({todayBtn:"linked",keyboardNavigation:!1,forceParse:!1,calendarWeeks:!0,autoclose:!0});
        $("#data_2 .input-group.date").datepicker({todayBtn:"linked",keyboardNavigation:!1,forceParse:!1,calendarWeeks:!0,autoclose:!0});

    });

</script>
<div class="col-md-12 ibox ibox-content">
  <div class="ibox-content form-horizontal m-t">
    <div class="form-group">
      <%= form_for(@giveaway,:html => {:class=>'form-horizontal m-t',:multipart => true}) do |f| %>

          <div class="form-group">
            <label class="col-sm-3 control-label">活动名称：</label>
            <div class="col-sm-5">
              <%= f.text_field :name,class:"form-control" %>
            </div>
          </div>
          <div class="form-group">

            <label class="col-sm-3 control-label">启用：</label>
            <div class="col-sm-5">
              <%= f.hidden_field :enable,class:"form-control", id:'enable' %>
              <label>
                <input type="checkbox" class="i-checks" id="enablecheck"></label>
            </div>
          </div>
          <div class="form-group" id="data_1">
            <label class="col-sm-3 control-label">开始时间：</label>

              <div class="input-group date col-sm-5">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <%= f.text_field :begindate,class:"form-control" %>
              </div>
          </div>
          <div class="form-group" id="data_2">
            <label class="col-sm-3 control-label">结束时间：</label>

            <div class="input-group date col-sm-5">
              <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
              <%= f.text_field :enddate,class:"form-control" %>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">合计购买数量：</label>
            <div class="col-sm-5">
              <%= f.text_field :buynum,class:"form-control" %>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">赠送商品：</label>
            <div class="col-sm-5">
              <%= f.text_field :giveproduct_id,class:"form-control",id:'giveproductid' %>
              <select class="form-control m-b" id="giveproductselect">
                <option value=0></option>
                <% @products.each do |product| %>
                    <option value=<%= product.id %> ><%= product.name %></option>
                <% end %>
              </select>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">赠送数量：</label>
            <div class="col-sm-5">
              <%= f.text_field :givenum,class:"form-control" %>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">限购一次：</label>
            <div class="col-sm-5">
              <%= f.hidden_field :once,class:"form-control", id:'once' %>
              <label>
                <input type="checkbox" class="i-checks" id="oncecheck"></label>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label"></label>
            <div class="col-sm-5 text-right">
              <%= f.submit '确定',class: "btn btn-w-m btn-primary ",id:'smt' %>&nbsp;<%= link_to "返回",admins_path,class: "btn btn-w-m btn-primary " %>
            </div>
          </div>
      <% end %>
    </div>




    <p>&nbsp;</p>
    <div class="row">
      <div class="col-sm-12">
        <span>参与活动商品</span>
        <hr style="margin-top:0px;">
      </div>
    </div>



    <div class="table-responsive m-t">
      <table class="table invoice-table">
        <thead>
        <tr>
          <th>产品名称</th>
          <th>操作</th>
        </tr>
        </thead>
        <tbody>

            <% @giveawayproducts.each do |giveawayproduct| %>
                <% product=Product.find(giveawayproduct.product_id) %>
                <tr>
                  <td>
                    <strong><%=product.name %></strong>
                  </td>
                  <td><%= link_to '删除', [giveawayproduct.giveaway,giveawayproduct], method: :delete, data: { confirm: '确认删除?' } %></td>
                </tr>
            <% end %>

        </tbody>
      </table>
    </div>


    <div class="ibox-content form-horizontal m-t">
      <div class="form-group">
        <%= form_for([@giveaway, @giveaway.giveawayproducts.build]) do |f| %>
            <div class="form-group">
              <label class="col-sm-8 control-label">产品名称：</label>
              <div class="col-sm-4">
                <%= f.hidden_field :product_id,class:'form-control',id:"productInput" %>
                <select class="form-control m-b" id="selectproduct">
                  <option value=0>请选择产品</option>
                  <% @products.each do |product| %>
                      <option value=<%= product.id %> ><%= product.name %></option>
                  <% end %>
                </select>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-8 control-label"></label>
              <div class="col-sm-4 text-right">
                <%= f.submit '确定', class:"btn btn-w-m btn-primary" %>

              </div>
            </div>
        <% end %>

      </div>
    </div>





    <div class="row">
      <div class="col-sm-12">
        <span>已参与活动商家</span>
        <hr style="margin-top:0px;">
      </div>
    </div>



    <div class="table-responsive m-t">
      <table class="table invoice-table">
        <thead>
        <tr>
          <th>商家名称</th>
          <th>参与次数</th>
          <th>操作</th>
        </tr>
        </thead>
        <tbody>

        <% @giveawaybusines.each do |giveawaybusine| %>
            <% busine=Busine.find(giveawaybusine.busine_id) %>
            <tr>
              <td>
                <strong><%=busine.name %></strong>
              </td>
              <td><%= giveawaybusine.times %></td>
              <td><%= link_to '删除', [giveawaybusine.giveaway,giveawaybusine], method: :delete, data: { confirm: '确认删除?' } %></td>
            </tr>
        <% end %>

        </tbody>
      </table>
    </div>


    <div class="ibox-content form-horizontal m-t">
      <div class="form-group">
        <%= form_for([@giveaway, @giveaway.giveawaybusines.build]) do |f| %>
            <div class="form-group">
              <label class="col-sm-8 control-label">商家名称：</label>
              <div class="col-sm-4">
                <%= f.hidden_field :busine_id,class:'form-control',id:"busineInput" %>
                <%= f.hidden_field :times,class:'form-control',value:'1' %>
                <select class="form-control m-b" id="selectbusine">
                  <option value=0>请选择商家</option>
                  <% @busines.each do |busine| %>
                      <option value=<%= busine.id %> ><%= busine.name %></option>
                  <% end %>
                </select>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-8 control-label"></label>
              <div class="col-sm-4 text-right">
                <%= f.submit '确定', class:"btn btn-w-m btn-primary" %>

              </div>
            </div>
        <% end %>

      </div>
    </div>




  </div>
</div>

app/views/giveaways/_form.html.erb
<script>
    $(document).ready(function(){

        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green'
        });

if($('#enable').val()==''){
    $('#enable').val('1');
}
        if($('#enable').val()== '0' ){
            $('#enablecheck').iCheck('uncheck');
        }else{
            $('#enablecheck').iCheck('check');
        }
            $('#enablecheck').on('ifChecked',function(event){
                $('#enable').val(1);
            });
        $('#enablecheck').on('ifUnchecked',function(event){
            $('#enable').val(0);
        });

        if($('#once').val()==''){
            $('#once').val('1');
        }

        if($('#once').val()== '0' ){
            $('#oncecheck').iCheck('uncheck');
        }else{
            $('#oncecheck').iCheck('check');
        }
        $('#oncecheck').on('ifChecked',function(event){
            $('#once').val(1);
        });
        $('#oncecheck').on('ifUnchecked',function(event){
            $('#once').val(0);
        });

        $('#buyproductselect').change(function(){
            $('#buyproductid').val($(this).val());
        });

        if($('#buyproductid').val()!=''){
            $('#buyproductselect').val($('#buyproductid').val());
        }

        $('#giveproductselect').change(function(){
            $('#giveproductid').val($(this).val());
        });

        if($('#giveproductid').val()!=''){
            $('#giveproductselect').val($('#giveproductid').val());
        }

        $('#selectproduct').change(function(){
            $('#productInput').val($(this).val());
        });


        $("#data_1 .input-group.date").datepicker({todayBtn:"linked",keyboardNavigation:!1,forceParse:!1,calendarWeeks:!0,autoclose:!0});
        $("#data_2 .input-group.date").datepicker({todayBtn:"linked",keyboardNavigation:!1,forceParse:!1,calendarWeeks:!0,autoclose:!0});

    });

</script>
<div class="col-md-12 ibox ibox-content">
  <div class="ibox-content form-horizontal m-t">
    <div class="form-group">
      <%= form_for(@giveaway,:html => {:class=>'form-horizontal m-t',:multipart => true}) do |f| %>

          <div class="form-group">
            <label class="col-sm-3 control-label">活动名称：</label>
            <div class="col-sm-5">
              <%= f.text_field :name,class:"form-control" %>
            </div>
          </div>
          <div class="form-group">

            <label class="col-sm-3 control-label">启用：</label>
            <div class="col-sm-5">
              <%= f.hidden_field :enable,class:"form-control", id:'enable' %>
              <label>
                <input type="checkbox" class="i-checks" id="enablecheck"></label>
            </div>
          </div>
          <div class="form-group" id="data_1">
            <label class="col-sm-3 control-label">开始时间：</label>

              <div class="input-group date col-sm-5">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <%= f.text_field :begindate,class:"form-control" %>
              </div>
          </div>
          <div class="form-group" id="data_2">
            <label class="col-sm-3 control-label">结束时间：</label>

            <div class="input-group date col-sm-5">
              <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
              <%= f.text_field :enddate,class:"form-control" %>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">合计购买数量：</label>
            <div class="col-sm-5">
              <%= f.text_field :buynum,class:"form-control" %>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">赠送商品：</label>
            <div class="col-sm-5">
              <%= f.text_field :giveproduct_id,class:"form-control",id:'giveproductid' %>
              <select class="form-control m-b" id="giveproductselect">
                <option value=0></option>
                <% @products.each do |product| %>
                    <option value=<%= product.id %> ><%= product.name %></option>
                <% end %>
              </select>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">赠送数量：</label>
            <div class="col-sm-5">
              <%= f.text_field :givenum,class:"form-control" %>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">限购一次：</label>
            <div class="col-sm-5">
              <%= f.hidden_field :once,class:"form-control", id:'once' %>
              <label>
                <input type="checkbox" class="i-checks" id="oncecheck"></label>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label"></label>
            <div class="col-sm-5 text-right">
              <%= f.submit '确定',class: "btn btn-w-m btn-primary ",id:'smt' %>&nbsp;<%= link_to "返回",admins_path,class: "btn btn-w-m btn-primary " %>
            </div>
          </div>
      <% end %>
    </div>


  </div>
</div>

app/views/giveaways/edit.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>编辑活动</h3>
    </div>
    <%= render 'editform', giveaway: @giveaway %>
  </div>
</div>
<%=render 'layerend' %>

app/views/giveaways/index.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>买满送活动</h3>
    </div>
    <div class="ibox-content">
      <table class="table table-hover table-bordered text-center">
        <thead>
        <tr>
          <th class="text-center">活动名称</th>
          <th class="text-center">是否生效</th>
          <th class="text-center">开始日期</th>
          <th class="text-center">结束日期</th>
          <th class="text-center">操作</th>
        </tr>
        </thead>
        <tbody>
        <% @giveaways.each do |giveaway| %>
            <tr>
              <td><%= giveaway.name %></td>
              <td>

                <%if giveaway.enable == 1 %>
                有效
                    <% else %>
                未生效
                <% end %>
              </td>
              <td>

<%= giveaway.begindate.strftime('%Y-%m-%d') %>
              </td>
              <td>
<%= giveaway.enddate.strftime('%Y-%m-%d') %>
              </td>

              <td><%= link_to '编辑',edit_giveaway_path(giveaway) %>
                &nbsp;
                <%= link_to '删除', giveaway, method: :delete, data: { confirm: '确认删除?' } %>
                    </td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <%= link_to "新增",new_giveaway_path,class: "btn btn-w-m btn-primary pull-right" %>
      <br>
    </div>
  </div>
</div>
<%=render 'layerend' %>

app/views/giveaways/new.html.erb
<%= render 'layerbegin' %>
<div class="col-lg-12">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <h3>新增买满送活动</h3>
    </div>
    <%= render 'form', giveaway: @giveaway %>
  </div>
</div>
<%=render 'layerend' %>